server:
  port: 8010

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/jianzheng?useUnicode=true&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    druid:
      initial-size: 2
      min-idle: 2
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 6000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      connection-properties: druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true
      # 配置监控统计拦截的filters
      filters: stat

# swagger
swagger:
  host: 127.0.0.1
  basic:
    enable: true
    username: jianzheng
    password: jianzheng!666@

jianzheng:
  # 默认上传根路径
  upload-base-path: /data/website/jianzheng/upload/
  # 图片访问根路径
  upload-base-url: http://localhost:${server.port}/upload/

product:
  #商品具体跳转地址
  url: http://localhost:${server.port}/api/product/info

#jsontoken
jwt:
  subject: com.jianzheng.server
  # 8小时 8 * 3600 * 1000
  life: 28800000
  secret: IOUsudlas60cWsLq4s1gKqwNp5gN48KRDjJ5.OTkwMiIsImlkIjoiaWRfMTAwMDEiLCJleHAiOjE1MjAzMjE2OTR
